using PatientPortal.SeedTool.Utilities;

namespace PatientPortal.SeedTool.Bogus;

/// <summary>
/// Custom Bogus dataset providing realistic medical data for seed generation.
/// </summary>
public static class HealthIssueData
{
    private static readonly string[] HealthIssueShortDescriptions =
    [
        "Abdominal Aortic Aneurysm",
        "Achilles Tendinopathy",
        "Acute Bronchitis",
        "Acute Cholecystitis",
        "Acute Lymphoblastic Leukemia",
        "Acute Myeloid Leukemia",
        "Acute Pancreatitis",
        "Acute Respiratory Infection",
        "Addison's Disease",
        "ADHD",
        "Alcohol-Related Liver Disease",
        "Allergic Conjunctivitis",
        "Allergic Rhinitis",
        "Alopecia",
        "Alzheimer's Disease",
        "Anaphylaxis",
        "Anemia",
        "Angina",
        "Angioedema",
        "Ankylosing Spondylitis",
        "Anorexia Nervosa",
        "Aortic Stenosis",
        "Aplastic Anemia",
        "Appendicitis",
        "Arterial Thrombosis",
        "Arthritis",
        "Asbestosis",
        "Asthma",
        "Astigmatism",
        "Ataxia",
        "Atopic Eczema",
        "Atrial Fibrillation",
        "Autism",
        "Bipolar Disorder",
        "Bladder Cancer",
        "Bowel Cancer",
        "Bowel Incontinence",
        "Brain Tumours",
        "Bronchiectasis",
        "Bulimia Nervosa",
        "Bursitis",
        "C. Difficile Infection",
        "Carpal Tunnel Syndrome",
        "Celiac Disease",
        "Cellulitis",
        "Cerebral Palsy",
        "Chest Infection",
        "Cholelithiasis (Gallstones)",
        "Chronic Back Pain",
        "Chronic Fatigue Syndrome",
        "Chronic Kidney Disease",
        "Chronic Pain",
        "Chronic Pancreatitis",
        "Cirrhosis",
        "Common Cold",
        "Concussion",
        "Congenital Heart Disease",
        "Conjunctivitis",
        "Constipation",
        "COPD",
        "Coronary Artery Disease",
        "Costochondritis",
        "Cough",
        "Crohn's Disease",
        "Cystic Fibrosis",
        "Cystitis",
        "Deep Vein Thrombosis",
        "Dehydration",
        "Delirium",
        "Dementia",
        "Dental Abscess",
        "Dermatitis Herpetiformis",
        "Diabetes Type 1",
        "Diabetes Type 2",
        "Diabetic Foot Issues",
        "Diabetic Ketoacidosis",
        "Diabetic Retinopathy",
        "Diverticular Disease",
        "Diverticulitis",
        "Dyspepsia",
        "Dysphagia",
        "Dystonia",
        "Ebola Virus Disease",
        "Eczema",
        "Elbow Fracture",
        "Epilepsy",
        "Esophageal Cancer",
        "Fibromyalgia",
        "Flat Feet",
        "Flu",
        "Food Allergy",
        "Food Poisoning",
        "Frozen Shoulder",
        "Functional Neurologic Disorder",
        "Fungal Nail Infection",
        "Ganglion Cyst",
        "Gastritis",
        "Gastroenteritis",
        "Generalized Anxiety Disorder",
        "GERD",
        "Glandular Fever",
        "Gout",
        "Gum Disease",
        "Hearing Loss",
        "Heart Attack",
        "Heart Block",
        "Heart Disease",
        "Heart Failure",
        "Heatstroke",
        "Hepatitis A",
        "Hepatitis B",
        "Hepatitis C",
        "Hiatus Hernia",
        "HIV",
        "Hodgkin Lymphoma",
        "Hydrocephalus",
        "Hyperglycemia",
        "Hyperhidrosis",
        "Hyperlipidemia",
        "Hypertension",
        "Hyperthyroidism",
        "Hypoglycemia",
        "Hypothermia",
        "Hypothyroidism",
        "Idiopathic Pulmonary Fibrosis",
        "Impetigo",
        "Inflammatory Bowel Disease",
        "Ingrown Toenail",
        "Insomnia",
        "Iron Deficiency",
        "Irritable Bowel Syndrome",
        "Joint Hypermobility",
        "Kidney Cancer",
        "Kidney Infection",
        "Kidney Stones",
        "Labyrinthitis",
        "Lactose Intolerance",
        "Laryngitis",
        "Legionnaires' Disease",
        "Lichen Planus",
        "Liver Cancer",
        "Liver Disease",
        "Long COVID",
        "Low Blood Pressure",
        "Lumbago",
        "Lung Cancer",
        "Lupus",
        "Lyme Disease",
        "Lymphedema",
        "Major Depressive Disorder",
        "Malaria",
        "Malnutrition",
        "Measles",
        "Meningitis",
        "Migraine",
        "Mouth Cancer",
        "Mouth Ulcer",
        "Multiple Sclerosis",
        "Multiple System Atrophy",
        "Mumps",
        "Muscular Dystrophy",
        "Myasthenia Gravis",
        "Myotonic Dystrophy",
        "Nasal and Sinus Cancer",
        "Neck Injury",
        "Neuroendocrine Tumors",
        "Non-Hodgkin Lymphoma",
        "Norovirus",
        "Obesity",
        "Obsessive Compulsive Disorder",
        "Oral Thrush",
        "Osteoarthritis",
        "Osteoarthritis of the Hand",
        "Osteoarthritis of the Hip",
        "Osteoarthritis of the Knee",
        "Osteoporosis",
        "Otitis Externa",
        "Otitis Media",
        "Pancreatic Cancer",
        "Panic Disorder",
        "Parkinson's Disease",
        "Patellofemoral Pain Syndrome",
        "Peptic Ulcer Disease",
        "Peripheral Neuropathy",
        "Personality Disorder",
        "Plantar Fasciitis",
        "Pleurisy",
        "Pneumonia",
        "Polymyalgia Rheumatica",
        "Post-Concussion Syndrome",
        "Post-Traumatic Stress Disorder",
        "Pressure Ulcers",
        "Psoriasis",
        "Psoriatic Arthritis",
        "Psychosis",
        "Psychotic Depression",
        "Pulmonary Hypertension",
        "Raynaud's Phenomenon",
        "Reactive Arthritis",
        "Restless Legs Syndrome",
        "Rheumatoid Arthritis",
        "Ringworm",
        "Rosacea",
        "Scabies",
        "Scarlet Fever",
        "Schizophrenia",
        "Sciatica",
        "Seasonal Affective Disorder",
        "Seasonal Allergies",
        "Sepsis",
        "Shingles",
        "Sickle Cell Disease",
        "Sinusitis",
        "Sjogren's Syndrome",
        "Skin Cancer",
        "Sleep Apnea",
        "Snapping Hip",
        "Social Anxiety Disorder",
        "Spinal Stenosis",
        "Sprain",
        "Stomach Cancer",
        "Stomach Ulcer",
        "Strain",
        "Stroke",
        "Subacromial Pain Syndrome",
        "Sunburn",
        "Supraventricular Tachycardia",
        "Syphilis",
        "Tendinitis",
        "Tennis Elbow",
        "Tension Headache",
        "Thrush",
        "Tinnitus",
        "Tonsillitis",
        "Tooth Decay",
        "Toothache",
        "Tourette's Syndrome",
        "Tuberculosis",
        "Ulcerative Colitis",
        "Urinary Incontinence",
        "Urinary Tract Infection",
        "Urticaria",
        "Varicose Eczema",
        "Varicose Veins",
        "Vascular Dementia",
        "Venous Leg Ulcer",
        "Vertigo",
        "Vitamin B12 Deficiency Anemia",
        "Vitamin D Deficiency",
        "Warts and Verrucas",
        "Whiplash",
        "Wrist Fracture",
        "Yellow Fever",
        "Zika Virus",
    ];

    /// <summary>
    /// Returns a randomly selected plausible health issue short description.
    /// Uses the <see cref="StringExtensions.Clamp"/> method to ensure the result does not exceed 30 characters,
    /// which is the maximum length for the ShortDescription property in the HealthIssue model.
    /// </summary>
    public static string GetARandomShortDescription() =>
        Rand.GetRandomElement(HealthIssueShortDescriptions).Clamp(30);
}
