using PatientPortal.SeedTool.Utilities;

namespace PatientPortal.SeedTool.Bogus;

/// <summary>
/// Custom Bogus dataset providing realistic medical data for seed generation.
/// </summary>
public static class TestTypeData
{
    private static readonly string[] TestTypes =
    [
        "24-hour Urine Collection",
        "Allergy Skin Test",
        "Arterial Blood Gas",
        "Basic Metabolic Panel",
        "Blood Ammonia",
        "Blood Culture",
        "Blood Glucose",
        "Blood Lactate",
        "Blood Pressure Check",
        "Blood Smear",
        "Blood Urea Nitrogen",
        "BNP (B-type Natriuretic Peptide)",
        "Bone Density (DEXA) Scan",
        "Calcium Level",
        "Capillary Blood Glucose",
        "Cardiac Enzymes",
        "CBC",
        "Cholesterol Test",
        "Colonoscopy",
        "Comprehensive Metabolic Panel",
        "Creatine Kinase",
        "Creatinine",
        "CRP (C-Reactive Protein)",
        "CT Scan - Abdomen",
        "CT Scan - Chest",
        "CT Scan - Head",
        "D-Dimer",
        "ECG",
        "Echocardiogram",
        "Electroencephalogram (EEG)",
        "Electrolyte Panel",
        "Electromyography (EMG)",
        "Endoscopy",
        "Erythrocyte Sedimentation Rate",
        "Fasting Blood Sugar",
        "Ferritin",
        "FOBT (Fecal Occult Blood Test)",
        "Folate Level",
        "Glucose Tolerance Test",
        "Hearing Test",
        "Helicobacter Pylori Test",
        "Hemoglobin A1c",
        "Holter Monitor",
        "Influenza Test",
        "INR (International Normalized Ratio)",
        "Iron Studies",
        "Lipid Panel",
        "Liver Biopsy",
        "Liver Function Panel",
        "Lumbar Puncture",
        "Magnesium Level",
        "Monospot Test",
        "MRI - Brain",
        "MRI - Knee",
        "MRI - Spine",
        "Oxygen Saturation",
        "Phosphate Level",
        "Platelet Count",
        "Potassium Level",
        "Prothrombin Time",
        "Pulmonary Angiogram",
        "Pulmonary Function Test",
        "Rapid Strep Test",
        "Renal Function Panel",
        "Reticulocyte Count",
        "Rheumatoid Factor",
        "SARS-CoV-2 PCR",
        "Skin Biopsy",
        "Spirometry",
        "Sputum Culture",
        "Thyroid Panel",
        "Thyroid Stimulating Hormone (TSH)",
        "Transferrin Saturation",
        "Triglycerides",
        "Troponin",
        "Ultrasound - Abdomen",
        "Ultrasound - Liver",
        "Ultrasound - Thyroid",
        "Uric Acid",
        "Urinalysis",
        "Urine Culture",
        "Vision Screening",
        "Vitamin B12 Level",
        "Vitamin D Level",
        "White Blood Cell Count",
        "Wound Culture",
        "X-Ray - Abdomen",
        "X-Ray - Chest",
        "X-Ray - Spine",
    ];

    /// <summary>
    /// Returns a randomly selected plausible medical test type name.
    /// </summary>
    public static string GetARandomTestType() => Rand.GetRandomElement(TestTypes);
}
