// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientPortal.Models;

namespace PatientPortal.Migrations
{
    [DbContext(typeof(PatientPortalContext))]
    [Migration("20211008111557_MessagingModels")]
    partial class MessagingModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("PatientPortal.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("PatientPortal.Models.HealthIssue", b =>
                {
                    b.Property<int>("HealthIssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LongDescription")
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("HealthIssueId");

                    b.HasIndex("PatientId");

                    b.ToTable("HealthIssues");
                });

            modelBuilder.Entity("PatientPortal.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("S2PConversationS2PId")
                        .HasColumnType("int");

                    b.Property<int?>("S2PId")
                        .HasColumnType("int");

                    b.Property<int?>("S2SConversationId")
                        .HasColumnType("int");

                    b.Property<int?>("S2SId")
                        .HasColumnType("int");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MessageId");

                    b.HasIndex("S2PConversationS2PId");

                    b.HasIndex("S2SConversationId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("PatientPortal.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Last4SSN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PatientPortal.Models.PatientStaffConnection", b =>
                {
                    b.Property<int>("PatientStaffConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PatientStaffConnectionId");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.ToTable("PatientStaffConnections");
                });

            modelBuilder.Entity("PatientPortal.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffUsername")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("StaffId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("PatientPortal.Models.StafftoPatientConversation", b =>
                {
                    b.Property<int>("S2PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MessagingPatient")
                        .HasColumnType("int");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("S2PId");

                    b.HasIndex("PatientId");

                    b.ToTable("StafftoPatientConversation");
                });

            modelBuilder.Entity("PatientPortal.Models.StafftoStaffConversation", b =>
                {
                    b.Property<int>("S2SConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("S2SConversationId");

                    b.ToTable("StafftoStaffConversation");
                });

            modelBuilder.Entity("PatientPortal.Models.TestHealthIssueAssociation", b =>
                {
                    b.Property<int>("TestHealthIssueAssociationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HealthIssueId")
                        .HasColumnType("int");

                    b.Property<int>("TestResultId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TestHealthIssueAssociationId");

                    b.HasIndex("HealthIssueId");

                    b.HasIndex("TestResultId");

                    b.ToTable("TestHealthIssueAssociations");
                });

            modelBuilder.Entity("PatientPortal.Models.TestResult", b =>
                {
                    b.Property<int>("TestResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TestResultId");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("PatientPortal.Models.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfVisit")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("VisitId");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("PatientPortal.Models.VisitHealthIssueAssociation", b =>
                {
                    b.Property<int>("VisitHealthIssueAssociationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HealthIssueId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("VisitHealthIssueAssociationId");

                    b.HasIndex("HealthIssueId");

                    b.HasIndex("VisitId");

                    b.ToTable("VisitHealthIssueAssociations");
                });

            modelBuilder.Entity("StaffStafftoPatientConversation", b =>
                {
                    b.Property<int>("MessagingStaffStaffId")
                        .HasColumnType("int");

                    b.Property<int>("PatientConversationsS2PId")
                        .HasColumnType("int");

                    b.HasKey("MessagingStaffStaffId", "PatientConversationsS2PId");

                    b.HasIndex("PatientConversationsS2PId");

                    b.ToTable("StaffStafftoPatientConversation");
                });

            modelBuilder.Entity("StaffStafftoStaffConversation", b =>
                {
                    b.Property<int>("MessagingStaffStaffId")
                        .HasColumnType("int");

                    b.Property<int>("StaffConversationsS2SConversationId")
                        .HasColumnType("int");

                    b.HasKey("MessagingStaffStaffId", "StaffConversationsS2SConversationId");

                    b.HasIndex("StaffConversationsS2SConversationId");

                    b.ToTable("StaffStafftoStaffConversation");
                });

            modelBuilder.Entity("PatientPortal.Models.Address", b =>
                {
                    b.HasOne("PatientPortal.Models.Patient", "Patient")
                        .WithOne("Address")
                        .HasForeignKey("PatientPortal.Models.Address", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientPortal.Models.HealthIssue", b =>
                {
                    b.HasOne("PatientPortal.Models.Patient", "Patient")
                        .WithMany("HealthIssues")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientPortal.Models.Message", b =>
                {
                    b.HasOne("PatientPortal.Models.StafftoPatientConversation", "S2PConversation")
                        .WithMany("Messages")
                        .HasForeignKey("S2PConversationS2PId");

                    b.HasOne("PatientPortal.Models.StafftoStaffConversation", "S2SConversation")
                        .WithMany("Messages")
                        .HasForeignKey("S2SConversationId");

                    b.Navigation("S2PConversation");

                    b.Navigation("S2SConversation");
                });

            modelBuilder.Entity("PatientPortal.Models.PatientStaffConnection", b =>
                {
                    b.HasOne("PatientPortal.Models.Patient", "Patient")
                        .WithMany("MedicalTeam")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientPortal.Models.Staff", "Staff")
                        .WithMany("Patients")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PatientPortal.Models.StafftoPatientConversation", b =>
                {
                    b.HasOne("PatientPortal.Models.Patient", null)
                        .WithMany("StaffConversations")
                        .HasForeignKey("PatientId");
                });

            modelBuilder.Entity("PatientPortal.Models.TestHealthIssueAssociation", b =>
                {
                    b.HasOne("PatientPortal.Models.HealthIssue", "HealthIssue")
                        .WithMany("AssociatedTestResults")
                        .HasForeignKey("HealthIssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientPortal.Models.TestResult", "TestResult")
                        .WithMany("AssociatedHealthIssues")
                        .HasForeignKey("TestResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthIssue");

                    b.Navigation("TestResult");
                });

            modelBuilder.Entity("PatientPortal.Models.TestResult", b =>
                {
                    b.HasOne("PatientPortal.Models.Patient", "Patient")
                        .WithMany("Tests")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientPortal.Models.Staff", "Staff")
                        .WithMany("TestsOrdered")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PatientPortal.Models.Visit", b =>
                {
                    b.HasOne("PatientPortal.Models.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientPortal.Models.Staff", "Staff")
                        .WithMany("Visits")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PatientPortal.Models.VisitHealthIssueAssociation", b =>
                {
                    b.HasOne("PatientPortal.Models.HealthIssue", "HealthIssue")
                        .WithMany("AssociatedVisits")
                        .HasForeignKey("HealthIssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientPortal.Models.Visit", "Visit")
                        .WithMany("AssociatedHealthIssues")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthIssue");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("StaffStafftoPatientConversation", b =>
                {
                    b.HasOne("PatientPortal.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("MessagingStaffStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientPortal.Models.StafftoPatientConversation", null)
                        .WithMany()
                        .HasForeignKey("PatientConversationsS2PId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StaffStafftoStaffConversation", b =>
                {
                    b.HasOne("PatientPortal.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("MessagingStaffStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientPortal.Models.StafftoStaffConversation", null)
                        .WithMany()
                        .HasForeignKey("StaffConversationsS2SConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientPortal.Models.HealthIssue", b =>
                {
                    b.Navigation("AssociatedTestResults");

                    b.Navigation("AssociatedVisits");
                });

            modelBuilder.Entity("PatientPortal.Models.Patient", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("HealthIssues");

                    b.Navigation("MedicalTeam");

                    b.Navigation("StaffConversations");

                    b.Navigation("Tests");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("PatientPortal.Models.Staff", b =>
                {
                    b.Navigation("Patients");

                    b.Navigation("TestsOrdered");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("PatientPortal.Models.StafftoPatientConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PatientPortal.Models.StafftoStaffConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PatientPortal.Models.TestResult", b =>
                {
                    b.Navigation("AssociatedHealthIssues");
                });

            modelBuilder.Entity("PatientPortal.Models.Visit", b =>
                {
                    b.Navigation("AssociatedHealthIssues");
                });
#pragma warning restore 612, 618
        }
    }
}
