# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

name: patientportal
services:

  mysql_db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ../mysql.env
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
      interval: 3s
      timeout: 30s
      retries: 5

  asp.net_app:
    depends_on:
      mysql_db:
        condition: service_healthy
    env_file:
      - ../.env
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile
    ports:
      - 5000:5000

volumes:
  mysql_data:

networks:
  default:
    name: patientportal_network