# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

name: patientportal
services:

  mysql_db:
    image: mysql:8.0
    command: --lower_case_table_names=1
    env_file:
      - ./mysql.env
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - "$DB_INIT_PATH:/docker-entrypoint-initdb.d/1.sql"
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
      interval: 5s
      timeout: 60s
      retries: 10

  asp.net_app:
    depends_on:
      mysql_db:
        condition: service_healthy
    image: ${IMAGE_NAME}
    env_file:
      - ./app.env
    ports:
      - 5000:5000
    restart: always

volumes:
  mysql_data:

networks:
  default:
    name: patientportal_network