// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientPortal.Models;

#nullable disable

namespace PatientPortal.Migrations
{
    [DbContext(typeof(PatientPortalContext))]
    [Migration("20260127221840_LinkStaffToIdentityUser")]
    partial class LinkStaffToIdentityUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("IdentityUser");
                });

            modelBuilder.Entity("PatientPortal.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("ZipCode")
                        .HasColumnType("longtext");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("PatientPortal.Models.Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ConversationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("WithPatient")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ConversationId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("PatientPortal.Models.ConversationParticipant", b =>
                {
                    b.Property<int>("ConversationParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ConversationParticipantId"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MessagingLinkId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ConversationParticipantId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("MessagingLinkId");

                    b.ToTable("ConversationParticipants");
                });

            modelBuilder.Entity("PatientPortal.Models.HealthIssue", b =>
                {
                    b.Property<int>("HealthIssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HealthIssueId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LongDescription")
                        .HasColumnType("longtext");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("HealthIssueId");

                    b.HasIndex("PatientId");

                    b.ToTable("HealthIssues");
                });

            modelBuilder.Entity("PatientPortal.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MessagingLinkId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("MessagingLinkId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("PatientPortal.Models.MessagingLink", b =>
                {
                    b.Property<int>("MessagingLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MessagingLinkId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MessagingLinkId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.HasIndex("StaffId")
                        .IsUnique();

                    b.ToTable("MessagingLinks");
                });

            modelBuilder.Entity("PatientPortal.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Last4SSN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PatientPortal.Models.PatientStaffConnection", b =>
                {
                    b.Property<int>("PatientStaffConnectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatientStaffConnectionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PatientStaffConnectionId");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.ToTable("PatientStaffConnections");
                });

            modelBuilder.Entity("PatientPortal.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StaffUsername")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("StaffId");

                    b.HasIndex("UserId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("PatientPortal.Models.TestHealthIssueAssociation", b =>
                {
                    b.Property<int>("TestHealthIssueAssociationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TestHealthIssueAssociationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HealthIssueId")
                        .HasColumnType("int");

                    b.Property<int>("TestResultId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TestHealthIssueAssociationId");

                    b.HasIndex("HealthIssueId");

                    b.HasIndex("TestResultId");

                    b.ToTable("TestHealthIssueAssociations");
                });

            modelBuilder.Entity("PatientPortal.Models.TestResult", b =>
                {
                    b.Property<int>("TestResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TestResultId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TestResultId");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("PatientPortal.Models.Unread", b =>
                {
                    b.Property<int>("UnreadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UnreadId"));

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<int>("MessagingLinkId")
                        .HasColumnType("int");

                    b.Property<bool>("WithPatient")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UnreadId");

                    b.HasIndex("MessageId");

                    b.HasIndex("MessagingLinkId");

                    b.ToTable("UnreadMessages");
                });

            modelBuilder.Entity("PatientPortal.Models.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfVisit")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("VisitId");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("PatientPortal.Models.VisitHealthIssueAssociation", b =>
                {
                    b.Property<int>("VisitHealthIssueAssociationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VisitHealthIssueAssociationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HealthIssueId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("VisitHealthIssueAssociationId");

                    b.HasIndex("HealthIssueId");

                    b.HasIndex("VisitId");

                    b.ToTable("VisitHealthIssueAssociations");
                });

            modelBuilder.Entity("PatientPortal.Models.Address", b =>
                {
                    b.HasOne("PatientPortal.Models.Patient", "Patient")
                        .WithOne("Address")
                        .HasForeignKey("PatientPortal.Models.Address", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientPortal.Models.ConversationParticipant", b =>
                {
                    b.HasOne("PatientPortal.Models.Conversation", "Conversation")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientPortal.Models.MessagingLink", "MessagingLink")
                        .WithMany("ParticipatingConversations")
                        .HasForeignKey("MessagingLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("MessagingLink");
                });

            modelBuilder.Entity("PatientPortal.Models.HealthIssue", b =>
                {
                    b.HasOne("PatientPortal.Models.Patient", "Patient")
                        .WithMany("HealthIssues")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientPortal.Models.Message", b =>
                {
                    b.HasOne("PatientPortal.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientPortal.Models.MessagingLink", "Sender")
                        .WithMany()
                        .HasForeignKey("MessagingLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PatientPortal.Models.MessagingLink", b =>
                {
                    b.HasOne("PatientPortal.Models.Patient", "Patient")
                        .WithOne("MessagingLink")
                        .HasForeignKey("PatientPortal.Models.MessagingLink", "PatientId");

                    b.HasOne("PatientPortal.Models.Staff", "Staff")
                        .WithOne("MessagingLink")
                        .HasForeignKey("PatientPortal.Models.MessagingLink", "StaffId");

                    b.Navigation("Patient");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PatientPortal.Models.PatientStaffConnection", b =>
                {
                    b.HasOne("PatientPortal.Models.Patient", "Patient")
                        .WithMany("MedicalTeam")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientPortal.Models.Staff", "Staff")
                        .WithMany("Patients")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PatientPortal.Models.Staff", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PatientPortal.Models.TestHealthIssueAssociation", b =>
                {
                    b.HasOne("PatientPortal.Models.HealthIssue", "HealthIssue")
                        .WithMany("AssociatedTestResults")
                        .HasForeignKey("HealthIssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientPortal.Models.TestResult", "TestResult")
                        .WithMany("AssociatedHealthIssues")
                        .HasForeignKey("TestResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthIssue");

                    b.Navigation("TestResult");
                });

            modelBuilder.Entity("PatientPortal.Models.TestResult", b =>
                {
                    b.HasOne("PatientPortal.Models.Patient", "Patient")
                        .WithMany("Tests")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientPortal.Models.Staff", "Staff")
                        .WithMany("TestsOrdered")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PatientPortal.Models.Unread", b =>
                {
                    b.HasOne("PatientPortal.Models.Message", "Message")
                        .WithMany("UnreadBy")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientPortal.Models.MessagingLink", "MessagingLink")
                        .WithMany("UnreadMessages")
                        .HasForeignKey("MessagingLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("MessagingLink");
                });

            modelBuilder.Entity("PatientPortal.Models.Visit", b =>
                {
                    b.HasOne("PatientPortal.Models.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientPortal.Models.Staff", "Staff")
                        .WithMany("Visits")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PatientPortal.Models.VisitHealthIssueAssociation", b =>
                {
                    b.HasOne("PatientPortal.Models.HealthIssue", "HealthIssue")
                        .WithMany("AssociatedVisits")
                        .HasForeignKey("HealthIssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientPortal.Models.Visit", "Visit")
                        .WithMany("AssociatedHealthIssues")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthIssue");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("PatientPortal.Models.Conversation", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PatientPortal.Models.HealthIssue", b =>
                {
                    b.Navigation("AssociatedTestResults");

                    b.Navigation("AssociatedVisits");
                });

            modelBuilder.Entity("PatientPortal.Models.Message", b =>
                {
                    b.Navigation("UnreadBy");
                });

            modelBuilder.Entity("PatientPortal.Models.MessagingLink", b =>
                {
                    b.Navigation("ParticipatingConversations");

                    b.Navigation("UnreadMessages");
                });

            modelBuilder.Entity("PatientPortal.Models.Patient", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("HealthIssues");

                    b.Navigation("MedicalTeam");

                    b.Navigation("MessagingLink");

                    b.Navigation("Tests");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("PatientPortal.Models.Staff", b =>
                {
                    b.Navigation("MessagingLink");

                    b.Navigation("Patients");

                    b.Navigation("TestsOrdered");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("PatientPortal.Models.TestResult", b =>
                {
                    b.Navigation("AssociatedHealthIssues");
                });

            modelBuilder.Entity("PatientPortal.Models.Visit", b =>
                {
                    b.Navigation("AssociatedHealthIssues");
                });
#pragma warning restore 612, 618
        }
    }
}
