name: Deploy to ECR

on:
  push:
    branches: [ deploy_to_ecr ]
  workflow_dispatch:

env:
  AWS_REGION: us-west-2                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: patientportal           # set this to your Amazon ECR repository name

permissions:
  contents: read
  id-token: write
  
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
  
    steps:
    - name: Check out code from deploy_to_ecr branch
      uses: actions/checkout@v4
      with:
        ref: deploy_to_ecr
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: PatientPortalDeployment
        aws-region: ${{ env.AWS_REGION }}
        mask-aws-account-id: true
        retry-max-attempts: 4

    - name: Container Build and Deploy
      id: container-deploy
      uses: ./.github/actions/update-container
      with:
        AWS_REGION: ${{ env.AWS_REGION }}
        INSTANCE_ID: ${{ secrets.AWS_PROJECTWEBSERVER_EC2_INSTANCE_ID }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        TARGET_DIR: './src/PatientPortal'
        DOCKERFILE_PATH: './src/PatientPortal/Dockerfile'
        DOCKER_COMPOSE_PATH: './Docker/docker-compose.deploy.yml'

    - name: Send Notifications
      if: ${{ always() }}
      env:
        JOB_STATUS: ${{ job.status }}
      uses: ./.github/actions/notifier
      with:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        STATUS: ${{ env.JOB_STATUS == 'success' && 'success' || 'failure' }}
        TITLE: '${{ github.repository }} Deployment ${{ env.JOB_STATUS }}'
        FIELDS: >
          {
            "Repository": "${{ github.repository }}",
            "Ref": "${{ github.ref_name }}",
            "User": "${{ github.triggering_actor }}",
            "Workflow": "${{ github.workflow }}"
          }
